### ISSUE TITLE
Missing manualRef in CRD

### ISSUE THREAD

**Issue by JesusTheHun** [brantburnett/couchbase-index-operator#5]
The doc mentions `manualRef` but when I try to apply I get `unknown field "manualRef"`. I guess https://github.com/brantburnett/couchbase-index-operator/blob/main/docs/install/v1.0.0.yaml is not up to date :/

**Comment by brantburnett** [comment]
This is actually a documentation error, it should be `manual` not `manualRef`. I will get that corrected. Thanks!
